// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Pi8KOBBzCBbukl64bT9z_7mNdFAc2Ek',
    appId: '1:93668678282:web:5b2553f175a5dca36dab73',
    messagingSenderId: '93668678282',
    projectId: 'scholarship-app-1286b',
    authDomain: 'scholarship-app-1286b.firebaseapp.com',
    storageBucket: 'scholarship-app-1286b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmeL77uEOIYpycf0y6-BbjO_VCBG60xto',
    appId: '1:93668678282:android:32777a3513a7fb026dab73',
    messagingSenderId: '93668678282',
    projectId: 'scholarship-app-1286b',
    storageBucket: 'scholarship-app-1286b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIwZ2NDVh0nOccvOL0VIcJ1iXUzLoWSFo',
    appId: '1:93668678282:ios:ffdac86e4e8154166dab73',
    messagingSenderId: '93668678282',
    projectId: 'scholarship-app-1286b',
    storageBucket: 'scholarship-app-1286b.firebasestorage.app',
    iosClientId: '93668678282-sgr4u6dg9d97u4cqqrs5o4pn0prtv0i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarSearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIwZ2NDVh0nOccvOL0VIcJ1iXUzLoWSFo',
    appId: '1:93668678282:ios:ffdac86e4e8154166dab73',
    messagingSenderId: '93668678282',
    projectId: 'scholarship-app-1286b',
    storageBucket: 'scholarship-app-1286b.firebasestorage.app',
    iosClientId: '93668678282-sgr4u6dg9d97u4cqqrs5o4pn0prtv0i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarSearch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Pi8KOBBzCBbukl64bT9z_7mNdFAc2Ek',
    appId: '1:93668678282:web:3c50db007ecf29066dab73',
    messagingSenderId: '93668678282',
    projectId: 'scholarship-app-1286b',
    authDomain: 'scholarship-app-1286b.firebaseapp.com',
    storageBucket: 'scholarship-app-1286b.firebasestorage.app',
  );
}
